package com.example.todonotion.data.keyword

import androidx.annotation.NonNull
import androidx.room.*

//https://kotlinlang.org/docs/data-classes.html#properties-declared-in-the-class-body
//Room queries are not case sensitive, you can omit explicitly defining a lowercase table name here.
@Entity
data class Keyword(
    // TODO: declare the id to be an autogenerated primary key
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    //search keyWord
    @NonNull @ColumnInfo(name = "key_name")
    val keyName: String,
    @NonNull @ColumnInfo(name = "completed")
    val isCompleted: Boolean = false,

){
    val isActive
        get() = !isCompleted
    val isEmpty
        get() = keyName.isEmpty()
}