package com.example.todonotion.data.Keyword

import androidx.annotation.NonNull
import androidx.room.*

//Room queries are not case sensitive, you can omit explicitly defining a lowercase table name here.
@Entity
data class Keyword(
    // TODO: declare the id to be an autogenerated primary key
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    //search keyWord
    @NonNull @ColumnInfo(name = "key_name")
    val keyName: String,

)